"use client";

import * as React from "react";
import { Copy, Check, Pencil, Save, X, RotateCcw } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { toast } from "@/lib/toast";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  generateRecruitmentResultsText,
  type RecruitmentResultsCaseData,
} from "@/lib/recruitment";

// ============================================================================
// TYPES
// ============================================================================

export interface RecruitmentResultsTextProps {
  /**
   * Case data needed for results generation
   */
  data: RecruitmentResultsCaseData;

  /**
   * Custom summary text (overrides auto-generated)
   */
  customText?: string;

  /**
   * Callback when custom text is saved
   */
  onSaveCustomText?: (text: string | undefined) => void;

  /**
   * Whether the component is in read-only mode
   */
  readOnly?: boolean;

  /**
   * Optional className for container
   */
  className?: string;
}

// ============================================================================
// COMPONENT
// ============================================================================

/**
 * RecruitmentResultsText Component
 *
 * Displays auto-generated DOL-compliant recruitment results text with:
 * - Copy to clipboard functionality with checkmark animation
 * - Edit mode to manually override the text
 * - Save/Cancel buttons in edit mode
 * - Revert to auto-generated with confirmation dialog
 * - "Custom" badge when manually edited (blue left border)
 *
 * @example
 * ```tsx
 * <RecruitmentResultsText
 *   data={{
 *     employerName: "Acme Corp",
 *     noticeOfFilingStartDate: "2024-01-15",
 *     // ... other fields
 *   }}
 *   customText={case.recruitmentSummaryCustom}
 *   onSaveCustomText={(text) => updateCase({ recruitmentSummaryCustom: text })}
 * />
 * ```
 */
export function RecruitmentResultsText({
  data,
  customText,
  onSaveCustomText,
  readOnly = false,
  className,
}: RecruitmentResultsTextProps) {
  // -------------------------------------------------------------------------
  // State
  // -------------------------------------------------------------------------
  const [isEditing, setIsEditing] = React.useState(false);
  const [editValue, setEditValue] = React.useState("");
  const [copied, setCopied] = React.useState(false);
  const [showRevertDialog, setShowRevertDialog] = React.useState(false);

  const textareaRef = React.useRef<HTMLTextAreaElement>(null);

  // -------------------------------------------------------------------------
  // Computed values
  // -------------------------------------------------------------------------
  const autoGeneratedText = React.useMemo(
    () => generateRecruitmentResultsText(data),
    [data]
  );

  const displayText = customText ?? autoGeneratedText;
  const isCustom = !!customText;

  // -------------------------------------------------------------------------
  // Handlers
  // -------------------------------------------------------------------------
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(displayText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy text:", err);
      toast.error("Failed to copy text to clipboard. Please try again.");
    }
  };

  const handleEdit = () => {
    setEditValue(displayText);
    setIsEditing(true);
    // Focus textarea after render
    setTimeout(() => {
      textareaRef.current?.focus();
      textareaRef.current?.select();
    }, 50);
  };

  const handleSave = () => {
    // If the edited text matches auto-generated, clear custom text
    const trimmedValue = editValue.trim();
    if (trimmedValue === autoGeneratedText.trim()) {
      onSaveCustomText?.(undefined);
    } else {
      onSaveCustomText?.(trimmedValue);
    }
    setIsEditing(false);
  };

  const handleCancel = () => {
    setIsEditing(false);
    setEditValue("");
  };

  const handleRevert = () => {
    setShowRevertDialog(true);
  };

  const confirmRevert = () => {
    onSaveCustomText?.(undefined);
    setShowRevertDialog(false);
    setIsEditing(false);
  };

  // Auto-resize textarea
  React.useEffect(() => {
    if (isEditing && textareaRef.current) {
      const textarea = textareaRef.current;
      textarea.style.height = "auto";
      textarea.style.height = `${textarea.scrollHeight}px`;
    }
  }, [isEditing, editValue]);

  // -------------------------------------------------------------------------
  // Render
  // -------------------------------------------------------------------------
  return (
    <>
      <div className={cn("space-y-3", className)}>
        {/* Header with actions */}
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <h4 className="text-sm font-semibold text-muted-foreground">
              Recruitment Results
            </h4>
            {isCustom && !isEditing && (
              <span className="inline-flex items-center rounded-md bg-blue-50 dark:bg-blue-900/20 px-2 py-0.5 text-xs font-medium text-blue-700 dark:text-blue-300 ring-1 ring-inset ring-blue-600/20">
                Custom
              </span>
            )}
          </div>

          {/* Action buttons */}
          {!readOnly && (
            <div className="flex items-center gap-1">
              {isEditing ? (
                <>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleCancel}
                    className="h-8 px-2 gap-1"
                  >
                    <X className="h-4 w-4" />
                    <span className="hidden sm:inline">Cancel</span>
                  </Button>
                  {isCustom && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleRevert}
                      className="h-8 px-2 gap-1 text-muted-foreground"
                    >
                      <RotateCcw className="h-4 w-4" />
                      <span className="hidden sm:inline">Revert</span>
                    </Button>
                  )}
                  <Button
                    variant="default"
                    size="sm"
                    onClick={handleSave}
                    className="h-8 px-2 gap-1"
                  >
                    <Save className="h-4 w-4" />
                    <span className="hidden sm:inline">Save</span>
                  </Button>
                </>
              ) : (
                <>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleCopy}
                    className="h-8 px-2 gap-1"
                    aria-label={copied ? "Copied!" : "Copy to clipboard"}
                  >
                    <AnimatePresence mode="wait">
                      {copied ? (
                        <motion.span
                          key="check"
                          initial={{ scale: 0.5, opacity: 0 }}
                          animate={{ scale: 1, opacity: 1 }}
                          exit={{ scale: 0.5, opacity: 0 }}
                          transition={{ duration: 0.15 }}
                        >
                          <Check className="h-4 w-4 text-green-600" />
                        </motion.span>
                      ) : (
                        <motion.span
                          key="copy"
                          initial={{ scale: 0.5, opacity: 0 }}
                          animate={{ scale: 1, opacity: 1 }}
                          exit={{ scale: 0.5, opacity: 0 }}
                          transition={{ duration: 0.15 }}
                        >
                          <Copy className="h-4 w-4" />
                        </motion.span>
                      )}
                    </AnimatePresence>
                    <span className="hidden sm:inline">
                      {copied ? "Copied!" : "Copy"}
                    </span>
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleEdit}
                    className="h-8 px-2 gap-1"
                  >
                    <Pencil className="h-4 w-4" />
                    <span className="hidden sm:inline">Edit</span>
                  </Button>
                </>
              )}
            </div>
          )}
        </div>

        {/* Text content */}
        <motion.div
          layout
          className={cn(
            "rounded-lg border-2 bg-muted/30 p-4 transition-colors",
            isCustom && !isEditing && "border-l-4 border-l-blue-500",
            isEditing && "border-primary"
          )}
        >
          {isEditing ? (
            <textarea
              ref={textareaRef}
              value={editValue}
              onChange={(e) => setEditValue(e.target.value)}
              className={cn(
                "w-full min-h-[200px] bg-transparent text-sm leading-relaxed",
                "resize-none outline-none",
                "font-mono"
              )}
              placeholder="Enter custom recruitment results text..."
            />
          ) : (
            <pre className="whitespace-pre-wrap text-sm leading-relaxed font-sans">
              {displayText}
            </pre>
          )}
        </motion.div>
      </div>

      {/* Revert Confirmation Dialog */}
      <Dialog open={showRevertDialog} onOpenChange={setShowRevertDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Revert to Auto-Generated Text?</DialogTitle>
            <DialogDescription>
              This will discard your custom recruitment results text and replace
              it with the automatically generated version. This action cannot be
              undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowRevertDialog(false)}
            >
              Cancel
            </Button>
            <Button variant="destructive" onClick={confirmRevert}>
              Revert
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
